#!/usr/bin/env python3
"""Push the repo to the droplet and rebuild the warehouse there.

The droplet - not the laptop - is the working environment. Every structural change
(dbt model, seed, sql/) must be applied there in the same session, so that "going
live" is a permissions change rather than a migration. This script is how that
happens; run it after any change to `dbt/`, `pipeline/`, `scripts/` or `sql/`.

    python deploy/sync_droplet.py              # sync + dbt seed + build + test
    python deploy/sync_droplet.py --no-build   # sync files only
    python deploy/sync_droplet.py --sql        # also apply sql/*.sql (idempotent DDL)
    python deploy/sync_droplet.py --select stg_smartmoving__report_lead_status+

Why SSH rather than a direct connection: the droplet's Postgres does not listen on
a public interface (by design), and `/opt` is owned by another application, so the
deployment lives under the service account's home directory.

Credentials are read from the repo `.env` and never written to the droplet's disk
except in APP_DIR/.env, which is chmod 600.
"""
from __future__ import annotations

import argparse
import io
import pathlib
import posixpath
import sys
import tarfile

import paramiko

REPO = pathlib.Path(__file__).resolve().parent.parent
APP_DIR = "/home/datawarehouse_user/datawarehouse"

# Directories mirrored to the droplet. dbt build artifacts and caches are excluded:
# they are machine-specific, and shipping a stale target/ makes dbt's state
# comparisons lie.
SYNC_DIRS = ["dbt", "pipeline", "scripts", "sql"]
EXCLUDE_PARTS = {
    "target", "logs", "dbt_packages", "__pycache__", ".dlt",
    ".pytest_cache", ".ruff_cache", ".git",
}
EXCLUDE_NAMES = {".user.yml", "api_call_log.jsonl"}
EXCLUDE_SUFFIX = (".pyc", ".duckdb", ".duckdb.wal")


def load_env() -> dict[str, str]:
    env: dict[str, str] = {}
    for line in (REPO / ".env").read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, v = line.split("=", 1)
            env[k.strip()] = v.strip()
    return env


def keep(path: pathlib.Path) -> bool:
    if EXCLUDE_PARTS & set(path.parts):
        return False
    if path.name in EXCLUDE_NAMES:
        return False
    return not path.name.endswith(EXCLUDE_SUFFIX)


def build_tar() -> tuple[bytes, int]:
    buf = io.BytesIO()
    n = 0
    with tarfile.open(fileobj=buf, mode="w:gz") as tar:
        for d in SYNC_DIRS:
            root = REPO / d
            if not root.is_dir():
                continue
            for f in sorted(root.rglob("*")):
                if not f.is_file():
                    continue
                rel = f.relative_to(REPO)
                if not keep(rel):
                    continue
                tar.add(f, arcname=rel.as_posix())
                n += 1
    return buf.getvalue(), n


def run(client: paramiko.SSHClient, script: str, timeout: int = 1800) -> int:
    stdin, stdout, stderr = client.exec_command("bash -s", timeout=timeout)
    stdin.write(script)
    stdin.channel.shutdown_write()
    for line in iter(stdout.readline, ""):
        sys.stdout.write(line)
        sys.stdout.flush()
    err = stderr.read().decode("utf-8", "replace")
    if err.strip():
        sys.stdout.write("--- stderr ---\n" + err + "\n")
    return stdout.channel.recv_exit_status()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-build", action="store_true", help="sync files only")
    ap.add_argument("--sql", action="store_true", help="apply sql/*.sql before building")
    ap.add_argument("--select", default=None, help="dbt --select expression")
    ap.add_argument("--full-refresh", action="store_true")
    args = ap.parse_args()

    env = load_env()
    blob, n_files = build_tar()
    print(f"==> packed {n_files} files ({len(blob) / 1024:.0f} KB)")

    cli = paramiko.SSHClient()
    cli.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    cli.connect(
        env["droplet_ssh_host"], username=env["droplet_ssh_user"],
        password=env["droplet_ssh_password"], timeout=30,
        look_for_keys=False, allow_agent=False,
    )

    sftp = cli.open_sftp()
    try:
        sftp.stat(APP_DIR)
    except IOError:
        sftp.mkdir(APP_DIR)
    remote_tar = posixpath.join(APP_DIR, "_sync.tar.gz")
    with sftp.open(remote_tar, "wb") as fh:
        fh.set_pipelined(True)
        fh.write(blob)

    # The host .env carries what dbt and the pipeline read. Written every sync so
    # a rotated credential propagates without anyone remembering to edit it.
    host_env = "\n".join([
        "# Generated by deploy/sync_droplet.py - do not edit by hand.",
        f"POSTGRES_HOST=localhost",
        f"POSTGRES_PORT=5432",
        f"POSTGRES_USER={env['droplet_platform_rw_user']}",
        f"POSTGRES_PASSWORD={env['droplet_platform_rw_password']}",
        f"POSTGRES_DB={env['droplet_db']}",
        f"postgres_host=localhost",
        f"postgres_port=5432",
        f"postgres_user={env['droplet_platform_rw_user']}",
        f"postgres_password={env['droplet_platform_rw_password']}",
        f"postgres_db={env['droplet_db']}",
        f"app_read_user={env['droplet_app_read_user']}",
        f"app_read_password={env['droplet_app_read_password']}",
        f"SMARTMOVING_API_KEY_LD={env['SMARTMOVING_API_KEY_LD']}",
        f"SMARTMOVING_API_KEY_LOCAL={env['SMARTMOVING_API_KEY_LOCAL']}",
        "",
    ])
    with sftp.open(posixpath.join(APP_DIR, ".env"), "w") as fh:
        fh.write(host_env)
    sftp.chmod(posixpath.join(APP_DIR, ".env"), 0o600)
    sftp.close()
    print(f"==> uploaded to {APP_DIR}")

    steps = [
        "set -euo pipefail",
        f"cd {APP_DIR}",
        # Replace only the synced trees, so target/ and the venv survive.
        #
        # scripts/ is NOT wiped. api_call_log.jsonl lives there and is the only
        # record of API quota already spent this month - excluding it from the
        # tarball is not enough if the directory itself is deleted first.
        # Overwriting file-by-file is sufficient: nothing in scripts/ is stale
        # state, unlike dbt's target/.
        "rm -rf dbt/models dbt/macros dbt/seeds pipeline sql",
        "tar xzf _sync.tar.gz && rm -f _sync.tar.gz",
        "if [ ! -x venv/bin/dbt ]; then python3 -m venv venv; "
        "  ./venv/bin/pip -q install --upgrade pip; "
        "  ./venv/bin/pip -q install 'dbt-postgres>=1.8,<1.10' 'dlt[postgres]>=1.4' 'requests>=2.31'; fi",
        "set -a; . ./.env; set +a",
        "./venv/bin/dbt --version | head -3",
    ]

    if args.sql:
        # Every sql/ file is idempotent DDL, so replaying them all is the cheapest
        # way to guarantee the droplet matches the repo.
        #
        # 00_bootstrap.sql is excluded: it creates schemas, roles and the RLS
        # control table, which requires a superuser. It ran once when the droplet
        # was provisioned and must not be part of the routine sync - platform_rw
        # cannot run it, so including it just fails the whole deploy.
        steps.append(
            'for f in $(ls sql/*.sql | grep -v "/00_"); do echo "-- $f"; '
            'PGPASSWORD="$POSTGRES_PASSWORD" psql -h localhost -U "$POSTGRES_USER" '
            '-d "$POSTGRES_DB" -v ON_ERROR_STOP=1 -q -f "$f"; done'
        )

    if not args.no_build:
        sel = f" --select {args.select}" if args.select else ""
        fr = " --full-refresh" if args.full_refresh else ""
        # flock: n8n will run builds on a schedule, and two overlapping dbt runs
        # against the same schemas corrupt each other's state.
        steps.append(
            "flock -w 900 /tmp/dw-dbt.lock -c '"
            f"cd {APP_DIR}/dbt && set -a && . {APP_DIR}/.env && set +a && "
            f"{APP_DIR}/venv/bin/dbt seed --profiles-dir . --target dev && "
            f"{APP_DIR}/venv/bin/dbt build --profiles-dir . --target dev{sel}{fr}"
            "'"
        )

    rc = run(cli, "\n".join(steps))
    cli.close()
    print(f"==> exit {rc}")
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
